### ISSUE TITLE
Form-Navigierbarkeit

### ISSUE THREAD

**Issue by Kepplinger** [Kepplinger/fit-anmeldesystem-client#9]
Es soll möglich sein zwischen den 4 Schritten mithilfe der **Navigations-Buttons** (auf der Seite unten) oder über die **Schritt-Anzeige** (auf der Seite oben) zu navigieren.

Dabei soll im _fit-registration.component.ts_ eine Logik implementiert werden, welche die Schrittänderung verwalten kann.

In der _fit-registration.component.html_ soll dafür gesorgt werden, dass immer das richtige Component angezeigt wird.

**Comment by pautzi** [comment]
Alles erledigt🎉
